#ifndef TOED_Constants_H
#define TOED_Constants_H

enum gModes {TOED_MAINMENU,TOED_PLAY,TOED_POSTGAME};
enum menuActions {TOED_MENUACTION_PLAYGAME,TOED_MENUACTION_PLAYGAME0,TOED_MENUACTION_PLAYGAME1,TOED_MENUACTION_PLAYGAME2,TOED_MENUACTION_MAINMENU};

#endif